// Generated by CoffeeScript 1.9.0
(function(document) {
  var lastTransfer;
  if (document.transferred != null) {
    lastTransfer = document.transferred[document.transferred.length - 1];
    return emit(lastTransfer.time, document.MalariaCaseID || document.caseid);
  }
});

//# sourceMappingURL=map.js.map
