// Generated by CoffeeScript 1.7.1
(function(document) {
  if (document.collection === "result" && (document.lastModifiedAt != null) && (document.user != null) && (document.MalariaCaseID != null)) {
    return emit(document.lastModifiedAt, [document.user, document.MalariaCaseID]);
  }
});

//# sourceMappingURL=map.map
