// Generated by CoffeeScript 1.6.2
var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

(function(doc) {
  var ignored, notCouch, notIgnored, value, _i, _len, _ref, _results;

  _results = [];
  for (_i = 0, _len = doc.length; _i < _len; _i++) {
    value = doc[_i];
    ignored = ["collection", "complete", "couchapp"];
    notIgnored = (_ref = !value, __indexOf.call(ignored, _ref) >= 0);
    notCouch = value.indexOf("_") !== 0;
    if (notIgnored && notCouch) {
      _results.push(emit(value, doc[value]));
    } else {
      _results.push(void 0);
    }
  }
  return _results;
});

/*
//@ sourceMappingURL=map.map
*/
