// Generated by CoffeeScript 1.3.1
var ResultsView,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

ResultsView = (function(_super) {
  var rowTemplate;

  __extends(ResultsView, _super);

  ResultsView.name = 'ResultsView';

  function ResultsView() {
    this.render = __bind(this.render, this);
    return ResultsView.__super__.constructor.apply(this, arguments);
  }

  ResultsView.prototype.initialize = function() {
    return this.question = new Question();
  };

  ResultsView.prototype.el = '#content';

  ResultsView.prototype.render = function() {
    var _this = this;
    this.$el.html("      <style>        table.results th.header, table.results td{          font-size:150%;        }      </style>      <h2>Partial Results</h2>      <table class='results notComplete tablesorter'>        <thead><tr>          " + _.map(this.question.summaryFieldNames(), function(summaryField) {
      return "<th class='header'>" + summaryField + "</th>";
    }).join("") + "          <th></th>        </tr></thead>        <tbody>        </tbody>      </table>      <h2>Complete Results</h2>      <table class='results complete tablesorter'>        <thead><tr>          " + _.map(this.question.summaryFieldNames(), function(summaryField) {
      return "<th class='header'>" + summaryField + "</th>";
    }).join("") + ("          <th></th>        </tr></thead>        <tbody>        </tbody>      </table>      <a href='#new/result/" + this.question.id + "'>Add new result</a>    "));
    $("a").button();
    $('table').tablesorter();
    $('table').addTableFilter({
      labelText: null
    });
    $("input[type=search]").textinput();
    if (Coconut.resultCollection == null) {
      Coconut.resultCollection = new ResultCollection();
    }
    return Coconut.resultCollection.fetch({
      success: function() {
        return Coconut.resultCollection.each(function(result, index) {
          return result.fetch({
            success: function() {
              var relevantKeys, templateData;
              relevantKeys = _this.question.summaryFieldKeys();
              if (relevantKeys.length === 0) {
                relevantKeys = _.difference(_.keys(result.toJSON()), ["_id", "_rev", "complete", "question", "collection"]);
              }
              if (result.question() === _this.question.id) {
                templateData = {
                  id: result.id,
                  resultFields: _.map(relevantKeys, function(key) {
                    var returnVal;
                    returnVal = result.get(key) || "";
                    if (typeof returnVal === "object") {
                      returnVal = JSON.stringify(returnVal);
                    }
                    return returnVal;
                  })
                };
                if (result.complete()) {
                  $("table.Complete tbody").append(rowTemplate(templateData));
                  $("table a").button();
                } else {
                  $("table.notComplete tbody").append(rowTemplate(templateData));
                  $("table a").button();
                }
              }
              if (index + 1 === Coconut.resultCollection.length) {
                return $("table").trigger("update");
              }
            }
          });
        });
      }
    });
  };

  rowTemplate = Handlebars.compile("    <tr>      {{#each resultFields}}        <td><a href='#edit/result/{{../id}}'>{{this}}</a></td>      {{/each}}      <td><a href='#delete/result/{{id}}' data-icon='delete' data-iconpos='notext'>Delete</a></td>    </tr>  ");

  return ResultsView;

})(Backbone.View);
