// Generated by CoffeeScript 1.4.0
var Reports;

Reports = (function() {

  function Reports(options) {
    if (options == null) {
      options = {};
    }
    this.startDate = options.startDate || moment(new Date).subtract('days', 7).format("YYYY-MM-DD");
    this.endDate = options.endDate || moment(new Date).format("YYYY-MM-DD");
    this.cluster = options.cluster || "off";
    this.summaryField1 = options.summaryField1;
    this.alertEmail = options.alertEmail || "false";
    this.locationTypes = "region, district, constituan, shehia".split(/, /);
    this.mostSpecificLocation = options.mostSpecificLocation || {
      type: "region",
      name: "ALL"
    };
  }

  Reports.prototype.getCases = function(options) {
    var _this = this;
    return $.couch.db(Coconut.config.database_name()).view("" + (Coconut.config.design_doc_name()) + "/caseIDsByDate", {
      startkey: moment(this.endDate).endOf("day").format(Coconut.config.get("date_format")),
      endkey: this.startDate,
      descending: true,
      include_docs: false,
      success: function(result) {
        var afterAllCasesDownloaded, caseIDs, cases;
        caseIDs = _.unique(_.pluck(result.rows, "value"));
        cases = _.map(caseIDs, function(caseID) {
          var malariaCase;
          malariaCase = new Case({
            caseID: caseID
          });
          malariaCase.fetch({
            success: function() {
              return afterAllCasesDownloaded();
            }
          });
          return malariaCase;
        });
        return afterAllCasesDownloaded = _.after(caseIDs.length, function() {
          cases = _.chain(cases).map(function(malariaCase) {
            if (_this.mostSpecificLocation.name === "ALL" || malariaCase.withinLocation(mostSpecificLocation)) {
              return malariaCase;
            }
          }).compact().value();
          return options.success(cases);
        });
      }
    });
  };

  Reports.prototype.alerts = function(callback) {
    var data,
      _this = this;
    data = {};
    return this.getCases({
      success: function(cases) {
        var IRSThresholdInMonths, districts;
        IRSThresholdInMonths = 6;
        data.followupsByDistrict = {};
        data.passiveCasesByDistrict = {};
        data.agesByDistrict = {};
        data.netsAndIRSByDistrict = {};
        data.travelByDistrict = {};
        data.totalPositiveCasesByDistrict = {};
        districts = WardHierarchy.allDistricts();
        districts.push("UNKNOWN");
        districts.push("ALL");
        _.each(districts, function(district) {
          data.followupsByDistrict[district] = {
            meedsCases: [],
            casesFollowedUp: []
          };
          data.passiveCasesByDistrict[district] = {
            indexCases: [],
            householdMembers: [],
            passiveCases: []
          };
          data.agesByDistrict[district] = {
            underFive: [],
            fiveToFifteen: [],
            fifteenToTwentyFive: [],
            overTwentyFive: [],
            unknown: []
          };
          data.netsAndIRSByDistrict[district] = {
            sleptUnderNet: [],
            recentIRS: []
          };
          data.travelByDistrict[district] = {
            travelReported: []
          };
          return data.totalPositiveCasesByDistrict[district] = [];
        });
        _.each(cases, function(malariaCase) {
          var district, _ref, _ref1;
          district = malariaCase.district() || "UNKNOWN";
          if (malariaCase["USSD Notification"] != null) {
            data.followupsByDistrict[district].meedsCases.push(malariaCase);
          }
          if (malariaCase["USSD Notification"] != null) {
            data.followupsByDistrict["ALL"].meedsCases.push(malariaCase);
          }
          if (((_ref = malariaCase["Household Members"]) != null ? _ref.length : void 0) > 0) {
            data.followupsByDistrict[district].casesFollowedUp.push(malariaCase);
          }
          if (((_ref1 = malariaCase["Household Members"]) != null ? _ref1.length : void 0) > 0) {
            data.followupsByDistrict["ALL"].casesFollowedUp.push(malariaCase);
          }
          if (malariaCase["Case Notification"] != null) {
            data.passiveCasesByDistrict[district].indexCases.push(malariaCase);
          }
          if (malariaCase["Case Notification"] != null) {
            data.passiveCasesByDistrict["ALL"].indexCases.push(malariaCase);
          }
          if (malariaCase["Household Members"] != null) {
            data.passiveCasesByDistrict[district].householdMembers = data.passiveCasesByDistrict[district].householdMembers.concat(malariaCase["Household Members"]);
          }
          if (malariaCase["Household Members"] != null) {
            data.passiveCasesByDistrict["ALL"].householdMembers = data.passiveCasesByDistrict["ALL"].householdMembers.concat(malariaCase["Household Members"]);
          }
          data.passiveCasesByDistrict[district].passiveCases = data.passiveCasesByDistrict[district].passiveCases.concat(malariaCase.positiveCasesAtHousehold());
          data.passiveCasesByDistrict["ALL"].passiveCases = data.passiveCasesByDistrict["ALL"].passiveCases.concat(malariaCase.positiveCasesAtHousehold());
          return _.each(malariaCase.positiveCasesIncludingIndex(), function(positiveCase) {
            var age;
            data.totalPositiveCasesByDistrict[district].push(positiveCase);
            data.totalPositiveCasesByDistrict["ALL"].push(positiveCase);
            if (positiveCase.Age != null) {
              age = parseInt(positiveCase.Age);
              if (age < 5) {
                data.agesByDistrict[district].underFive.push(positiveCase);
                data.agesByDistrict["ALL"].underFive.push(positiveCase);
              } else if (age < 15) {
                data.agesByDistrict[district].fiveToFifteen.push(positiveCase);
                data.agesByDistrict["ALL"].fiveToFifteen.push(positiveCase);
              } else if (age < 25) {
                data.agesByDistrict[district].fifteenToTwentyFive.push(positiveCase);
                data.agesByDistrict["ALL"].fifteenToTwentyFive.push(positiveCase);
              } else if (age >= 25) {
                data.agesByDistrict[district].overTwentyFive.push(positiveCase);
                data.agesByDistrict["ALL"].overTwentyFive.push(positiveCase);
              }
            } else {
              if (!positiveCase.age) {
                data.agesByDistrict[district].unknown.push(positiveCase);
              }
              if (!positiveCase.age) {
                data.agesByDistrict["ALL"].unknown.push(positiveCase);
              }
            }
            if (positiveCase.SleptunderLLINlastnight === "Yes" || positiveCase.IndexcaseSleptunderLLINlastnight === "Yes") {
              data.netsAndIRSByDistrict[district].sleptUnderNet.push(positiveCase);
              data.netsAndIRSByDistrict["ALL"].sleptUnderNet.push(positiveCase);
            }
            if (positiveCase.LastdateofIRS && positiveCase.LastdateofIRS.match(/\d\d\d\d-\d\d-\d\d/)) {
              if ((new moment).subtract('months', Coconut.IRSThresholdInMonths) < (new moment(positiveCase.LastdateofIRS))) {
                data.netsAndIRSByDistrict[district].recentIRS.push(positiveCase);
                data.netsAndIRSByDistrict["ALL"].recentIRS.push(positiveCase);
              }
            }
            if (positiveCase.TravelledOvernightinpastmonth === "Yes" || positiveCase.OvernightTravelinpastmonth === "Yes") {
              data.travelByDistrict[district].travelReported.push(positiveCase);
              return data.travelByDistrict["ALL"].travelReported.push(positiveCase);
            }
          });
        });
        _.each(data.followupsByDistrict, function(values, district) {
          return data.followupsByDistrict[district].meedsCasesFollowedUp = _.intersection(data.followupsByDistrict[district].meedsCases, data.followupsByDistrict[district].casesFollowedUp);
        });
        return callback(data);
      }
    });
  };

  return Reports;

})();
