// Generated by CoffeeScript 1.9.1
(function(doc) {
  var results, value;
  if (doc.collection === "result") {
    results = [];
    for (value in doc) {
      if (value.indexOf("_") !== 0 && value !== "collection" && value !== "complete" && value !== "couchapp") {
        results.push(emit(value, doc[value]));
      } else {
        results.push(void 0);
      }
    }
    return results;
  }
});

//# sourceMappingURL=map.js.map
