// Generated by CoffeeScript 1.9.0
(function(document) {
  if (document.collection === "result") {
    return emit(document.question + ':' + document.lastModifiedAt, null);
  }
});

//# sourceMappingURL=map.js.map
