// Generated by CoffeeScript 1.6.2
(function(doc) {
  var id;

  if (doc.ClientID) {
    emit(doc.ClientID, null);
  }
  if (doc.IDLabel) {
    id = doc.IDLabel.replace(/-|\n/g, "");
    if (id !== "") {
      return emit(id, null);
    }
  }
});

/*
//@ sourceMappingURL=map.map
*/
