// Generated by CoffeeScript 1.8.0
(function(doc) {
  if (doc.ClientID) {
    emit(doc.ClientID, null);
  }
  if (doc.IDLabel) {
    if (doc.IDLabel !== "") {
      return emit(doc.IDLabel, null);
    }
  }
});

//# sourceMappingURL=map.js.map
