// Generated by CoffeeScript 1.8.0
(function(doc) {
  if (doc.action && (doc.action === "sendToCloud" || doc.action === "getFromCloud")) {
    return emit(doc.time, doc.user);
  }
});

//# sourceMappingURL=map.js.map
