// Generated by CoffeeScript 1.6.2
var ScanBarcodeView, _ref,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

ScanBarcodeView = (function(_super) {
  __extends(ScanBarcodeView, _super);

  function ScanBarcodeView() {
    this.render = __bind(this.render, this);    _ref = ScanBarcodeView.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  ScanBarcodeView.prototype.el = '#content';

  ScanBarcodeView.prototype.events = {
    "change #barcode": "handleBarcode"
  };

  ScanBarcodeView.prototype.render = function() {
    return this.$el.html("      <h1>Scan Client Barcode</h1>      <input id='barcode' name='barcode' type='text'></input>    ");
  };

  ScanBarcodeView.prototype.handleBarcode = function() {
    var barcodeValue;

    barcodeValue = $("[name=barcode]").val();
    Coconut.loginView.callback = {
      success: function() {
        return Coconut.router.navigate("/summary/" + barcodeValue, true);
      }
    };
    return Coconut.loginView.render();
  };

  return ScanBarcodeView;

})(Backbone.View);

/*
//@ sourceMappingURL=ScanBarcodeView.map
*/
