// Generated by CoffeeScript 1.7.1
(function(doc) {
  if (doc.hf && (!doc.SMSSent)) {
    if ((doc.source != null) && (doc.source === "parallel sim" || doc.source === "textit")) {

    } else {
      return emit(doc.date, null);
    }
  }
});

//# sourceMappingURL=map.map
