// Generated by CoffeeScript 1.6.2
(function(doc) {
  if (doc.DateofPositiveResults) {
    emit(doc.DateofPositiveResults, doc.MalariaCaseID);
  }
  if (doc.MalariaTestResult === "PF" || doc.MalariaTestResult === "Mixed") {
    emit(doc.lastModifiedAt, doc.MalariaCaseID);
  }
  if (doc.caseid) {
    return emit(doc.date, doc.caseid);
  }
});

/*
//@ sourceMappingURL=map.map
*/
