// Generated by CoffeeScript 1.7.1
(function(doc) {
  if (doc.collection && doc.collection === "user") {
    return emit(doc.district, [doc.name, doc._id.substring(5)]);
  }
});

//# sourceMappingURL=map.map
