(document) ->
  if document.collection is "result" and document.question? and document.createdAt?
    # Generated from http://coconut.zmcp.org/spreadsheet_header
    #

    fields = {
      "Case Notification" : [
         "FacilityName",
         "LostToFollowup",
         "MalariaCaseID",
         "Name",
         "Shehia",
         "_id",
         "_rev",
         "collection",
         "complete",
         "createdAt",
         "lastModifiedAt",
         "question",
         "savedBy",
         "transferred",
         "user"
      ],
      "Household" : [
         "ContactMobilepatientrelative",
         "CouponNumbers",
         "FollowupNeighbors",
         "Haveyougivencouponsfornets",
         "HeadofHouseholdName",
         "HouseholdLocation-accuracy",
         "HouseholdLocation-altitude",
         "HouseholdLocation-altitudeAccuracy",
         "HouseholdLocation-description",
         "HouseholdLocation-heading",
         "HouseholdLocation-latitude",
         "HouseholdLocation-longitude",
         "HouseholdLocation-timestamp",
         "IndexcaseIfpatientisfemale1545yearsofageissheispregant",
         "IndexcasePatient",
         "IndexcasePatientscurrentstatus",
         "IndexcasePatientstreatmentstatus",
         "IndexcaseSleptunderLLINlastnight",
         "LastdateofIRS",
         "LostToFollowup",
         "MalariaCaseID",
         "NumberofHouseholdMembersTreatedforMalariaWithinPastWeek",
         "NumberofHouseholdMemberswithFeverorHistoryofFeverWithinPastWeek",
         "NumberofLLIN",
         "NumberofSleepingPlacesbedsmattresses",
         "Numberofotherhouseholdswithin50stepsofindexcasehousehold",
         "Reasonforvisitinghousehold",
         "ShehaMjumbe",
         "Shehia",
         "TotalNumberofResidentsintheHousehold",
         "Village",
         "_id",
         "_rev",
         "collection",
         "complete",
         "createdAt",
         "lastModifiedAt",
         "question",
         "savedBy",
         "transferred",
         "user"
      ],
      "USSD Notification" : [
         "LostToFollowup",
         "SMSSent",
         "_id",
         "_rev",
         "caseid",
         "collection",
         "createdAt",
         "date",
         "facility_district",
         "hasCaseNotification",
         "hf",
         "lastModifiedAt",
         "name",
         "positive_test_date",
         "shehia",
         "source",
         "source_phone",
         "type",
         "user"
      ],
      "Household Members" : [
         "Age",
         "AgeinYearsorMonths",
         "Comments",
         "CurrentBodyTemperatureC",
         "Fevercurrentlyorinthelasttwoweeks",
         "FirstName",
         "HeadofHouseholdName",
         "Ifyeslistallplacestravelled",
         "LastName",
         "MalariaCaseID",
         "MalariaTestResult",
         "OvernightTravelinpastmonth",
         "ReferredtoHealthFacility",
         "ResidentofShehia",
         "Sex",
         "SleptunderLLINlastnight",
         "TreatmentProvided",
         "_id",
         "_rev",
         "collection",
         "complete",
         "createdAt",
         "lastModifiedAt",
         "question",
         "savedBy",
         "transferred",
         "user"
      ],
      "Facility" : [
         "Age",
         "AgeinMonthsorYears",
         "CaseIDforotherhouseholdmemberthattestedpositiveatahealthfacility",
         "CommentRemarks",
         "ContactMobilepatientrelative",
         "DateofPositiveResults",
         "FacilityName",
         "FirstName",
         "Hassomeonefromthesamehouseholdrecentlytestedpositiveatahealthfacility",
         "HeadofHouseholdName",
         "IfYESlistALLplacestravelled",
         "LastName",
         "LostToFollowup",
         "MalariaCaseID",
         "MiddleName",
         "ParasiteSpecies",
         "ReferenceinOPDRegister",
         "Sex",
         "ShehaMjumbe",
         "Shehia",
         "TravelledOvernightinpastmonth",
         "TreatmentGiven",
         "Village",
         "_id",
         "_rev",
         "collection",
         "complete",
         "createdAt",
         "lastModifiedAt",
         "question",
         "savedBy",
         "transferred",
         "user"
      ]
    }


    data = for field in fields[document.question]
      document[field] or ""

    emit [document.question,document.createdAt], data
