// Generated by CoffeeScript 1.9.1
(function(doc) {
  if (doc.MalariaCaseID) {
    emit(doc.MalariaCaseID, null);
  }
  if (doc.caseid) {
    return emit(doc.caseid, null);
  }
});

//# sourceMappingURL=map.js.map
