// Generated by CoffeeScript 1.6.2
(function(doc) {
  if (doc.MalariaCaseID) {
    emit(doc.MalariaCaseID, null);
  }
  if (doc.caseid) {
    return emit(doc.caseid, null);
  }
});

/*
//@ sourceMappingURL=map.map
*/
